Vagrant.configure("2") do |config|
  
  config.vm.provision "shell", inline: <<-SHELL
    # Agregar el usuario 'ansible'
    sudo wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
    sudo dpkg -i zabbix-release_6.0-4+ubuntu20.04_all.deb
    sudo apt-get update
    # Install Zabbix server, MySQL, and other components
    sudo apt-get install -y zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent mysql-server
  
    # Log into MySQL and create the Zabbix database and user
    sudo mysql -uroot -e "CREATE DATABASE zabbix character set utf8mb4 collate utf8mb4_bin;"
    sudo mysql -uroot -e "CREATE USER 'zabbix'@'localhost' IDENTIFIED BY 'password';"
    sudo mysql -uroot -e "GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'localhost';"
    sudo mysql -uroot -e "SET GLOBAL log_bin_trust_function_creators = 1;"
    # Load Zabbix database schema
    sudo zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | sudo mysql --default-character-set=utf8mb4 -uzabbix -ppassword zabbix
    # Disable log_bin_trust_function_creators
    sudo mysql -uroot -e "SET GLOBAL log_bin_trust_function_creators = 0;"
    # Configure Zabbix server
    sudo sed -i 's/^# DBPassword=/DBPassword=password/' /etc/zabbix/zabbix_server.conf
    # Restart services
    sudo systemctl restart zabbix-server zabbix-agent apache2
    sudo systemctl enable zabbix-server zabbix-agent apache2
    SHELL

  config.vm.define "zabbix-server-k8s" do |vm|
    vm.vm.box = "ubuntu/focal64"
    vm.vm.network "private_network", ip: "192.168.56.100"
    vm.vm.hostname = "zabbix-server-k8s" 
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
