Vagrant.configure("2") do |config|
  num_vms = 4  # Número de máquinas virtuales a crear
  ansible_public_key = File.read("../ansible/key_rsa.pub")
  config.vm.provision "shell", inline: <<-SHELL
    # Agregar el usuario 'ansible'
    sudo useradd -m -s /bin/bash ansible
    sudo mkdir -p /home/ansible/.ssh
    echo "#{ansible_public_key}" > /home/ansible/.ssh/authorized_keys
    sudo chown -R ansible:ansible /home/ansible/.ssh
    sudo chmod 700 /home/ansible/.ssh
    sudo chmod 600 /home/ansible/.ssh/authorized_keys
    sudo wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
    sudo dpkg -i zabbix-release_6.0-4+ubuntu20.04_all.deb
    sudo apt-get update
    export DEBIAN_FRONTEND=noninteractive; sudo apt-get install tmux stressapptest
    # Agregar permiso NOPASSWD para ansible
    echo "ansible ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/ansible
  SHELL

  (1..num_vms).each do |i|
    config.vm.define "vm#{i}" do |vm|
      vm.vm.box = "ubuntu/focal64"
      vm.vm.network "private_network", ip: "192.168.56.20#{i}"
      vm.vm.hostname = "vm#{i}" 
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  end

  config.vm.define "zabbix-server" do |vm|
    vm.vm.box = "ubuntu/focal64"
    vm.vm.network "private_network", ip: "192.168.56.200"
    vm.vm.hostname = "zabbix-server" 
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end
    vm.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get --download-only install zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent zabbix-get mysql-server -y
    SHELL
  end
end
